apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: screenshot-service
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/gpu: nvidia-l4
        run.googleapis.com/gpu-count: "1"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
        - image: europe-west4-docker.pkg.dev/virtual-venue-stg-7102ffeb/screenshot-service/screenshot-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30 