version: '3.8'

services:
  screenshot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN
