services:
  screenshot-service:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN